server:
  port: ${PORT:8300}
spring:
  thymeleaf:
    cache: false
    prefix:
      classpath: /templates/
    suffix: .html
  application:
    name: cadastro-de-clientes
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
