server:
  port: ${PORT:8100}
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_URL:localhost:3306}/sales?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useTimezone=true&serverTimezone=UTC
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  application:
    name: endereco-api
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}